apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-app
  labels:
    app: wil-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wil-app
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
        - name: wil42
          image: wil42/playground:v2
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: wil-app
spec:
  selector:
    app: wil-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8888
