Vagrant.require_version ">= 2.4.5"

Vagrant.configure(2) do |config|
  config.vm.box = "alvistack/ubuntu-24.04"
  config.vm.box_version = "20250517.1.1"

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", SharedFoldersEnableSymlinksCreate: true

  config.vm.define "iounejjaS" do |control|
    control.vm.hostname = "iounejjaS"
    control.vm.network "private_network", ip: "192.168.56.110"

    control.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2

      v.customize ["modifyvm", :id, "--name", "iounejjaS"]
    end

    control.vm.provision "shell", path: './scripts/server.sh'
  end
end
