Vagrant.configure(2) do |config|
	config.vm.box = 'generic/alpine318'
	config.vm.box_url = 'https://app.vagrantup.com/generic/boxes/alpine318'
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

	config.vm.define "iounejjaS" do |control|
		control.vm.hostname = "iounejjaS"
		control.vm.network "private_network", ip: "192.168.56.110"

		control.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1

			v.customize ["modifyvm", :id, "--name", "iounejjaS"]
		end

		control.vm.provision "shell", path: './scripts/server.sh'
	end
end
