Vagrant.configure(2) do |config|
	config.vm.box = 'generic/alpine318'
	config.vm.box_url = 'https://app.vagrantup.com/generic/boxes/alpine318'
	config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

	config.vm.define "bonus-vagrant" do |control|
		control.vm.hostname = "bonus-vagrant"
		control.vm.network "private_network", ip: "192.168.56.200"

		control.vm.provider "virtualbox" do |v|
			v.memory = 4096
			v.cpus = 4

			v.customize ["modifyvm", :id, "--name", "bonus-vagrant"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		end

		control.vm.provision "shell", path: './scripts/setup.sh'
	end
end
