Vagrant.require_version ">= 2.4.5"

Vagrant.configure(2) do |config|
  config.vm.box = "alvistack/ubuntu-24.04"
  config.vm.box_version = "20250517.1.1"
  
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.define "p3-vagrant" do |control|
    control.vm.hostname = "p3-vagrant"
    control.vm.network "private_network", ip: "192.168.56.200"

    control.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2

      v.customize ["modifyvm", :id, "--name", "p3-vagrant"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    control.vm.provision "shell", path: './scripts/setup.sh'
  end
end
